spring.datasource.url=jdbc:postgresql://localhost:5432/clinica_db_local
spring.datasource.username=postgres
spring.datasource.password=tcc
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Configura\u00E7\u00E3o para executar scripts SQL de inicializa\u00E7\u00E3o
# spring.jpa.defer-datasource-initialization=true
# spring.sql.init.mode=always

# Cache em mem\u00F3ria para desenvolvimento local
# spring.cache.type=simple

# Desabilitar Redis no ambiente local
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

#${BD_DATASOURCE_PASSWORD}
